#define PIN_TOF_LEFT_RESET 4
#define PIN_TOF_CENTER_RESET 7
#define PIN_TOF_RIGHT_RESET 8

#define PIN_LED1 A3
#define PIN_LED2 A2
#define PIN_BUTTON A1

#define PIN_ENCODER_LEFT_A 11
#define PIN_ENCODER_LEFT_B 2
#define PIN_ENCODER_RIGHT_A 12
#define PIN_ENCODER_RIGHT_B 3

#define PIN_MOTOR_LEFT_1 9
#define PIN_MOTOR_LEFT_2 10
#define PIN_MOTOR_RIGHT_1 5
#define PIN_MOTOR_RIGHT_2 6
